cookie:
  expiry_days: 30
  key: your_very_strong_random_secret_key_here_32_chars_or_mor70c3f08fdfad5d67e6b3b6eee728e84109bb7dba800bcf9143666752aa1f9ef6e
  name: pcc_render_cookie
credentials:
  usernames:
    mtomas:
      email: manuel.tomas.estarlich@gmail.com
      failed_login_attempts: 0
      first_name: Manuel
      last_name: Tomas
      name: Manuel Tomas
      password: $2b$12$plQ4F8JrTfY0l0drWXee5.WaU/7qKA3hr1/TxE1IaMYe6j/144njK
      password_hint: '*****6*'
      roles: null
    jcsanchez:
      email: info@ossienaturals.com
      first_name: Jesica
      last_name: Cabrera
      logged_in: false
      password: $2b$12$plQ4F8JrTfY0l0drWXee5.WaU/7qKA3hr1/TxE1IaMYe6j/144njK
      password_hint: '*****6*'
preauthorized:
  emails: 
  - manuel.tomas.estarlich@gmail.com
  - info@ossienaturals.com
