"""Add correct wholesale fee attributes to Product model

Revision ID: 5260605ee307
Revises: cc4ff4749959
Create Date: 2025-06-09 16:30:25.671460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5260605ee307'
down_revision: Union[str, None] = 'cc4ff4749959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('production_run_components')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_run_components',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('production_run_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('inventoryitem_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity_deducted_grams', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('production_run_components_pkey'))
    )
    # ### end Alembic commands ###
