"""Add total_monthly_items to GlobalCosts

Revision ID: cc4ff4749959
Revises: 61ae13442253
Create Date: 2025-06-08 17:03:36.141442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc4ff4749959'
down_revision: Union[str, None] = '61ae13442253'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_costs', sa.Column('total_monthly_items_for_rent_utilities', sa.Integer(), nullable=False, server_default='1000'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_costs', 'total_monthly_items_for_rent_utilities')
    op.create_table('production_run_components',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('production_run_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('inventoryitem_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity_deducted_grams', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('production_run_components_pkey'))
    )
    # ### end Alembic commands ###
