"""Add Supplier model and refactor Inventory Item model

Revision ID: e0217de68882
Revises: 5260605ee307
Create Date: 2025-06-09 16:57:10.687432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0217de68882'
down_revision: Union[str, None] = '5260605ee307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_supplier_name')
    )
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    op.create_table('inventoryitem_supplier_association',
    sa.Column('inventoryitem_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inventoryitem_id'], ['inventoryitems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.UniqueConstraint('inventoryitem_id', 'supplier_id', name='uq_inventoryitem_supplier')
    )
    op.add_column('inventoryitems', sa.Column('description', sa.Text(), nullable=True))
    op.drop_constraint(op.f('uq_user_inventoryitem_provider'), 'inventoryitems', type_='unique')
    op.create_unique_constraint('uq_user_inventoryitem_name', 'inventoryitems', ['user_id', 'name'])
    op.drop_column('inventoryitems', 'provider')
    op.drop_column('inventoryitems', 'price_url')
    op.drop_column('inventoryitems', 'price_per_unit')
    op.drop_column('inventoryitems', 'unit_quantity_kg')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventoryitems', sa.Column('unit_quantity_kg', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=False))
    op.add_column('inventoryitems', sa.Column('price_per_unit', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('inventoryitems', sa.Column('price_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('inventoryitems', sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_user_inventoryitem_name', 'inventoryitems', type_='unique')
    op.create_unique_constraint(op.f('uq_user_inventoryitem_provider'), 'inventoryitems', ['user_id', 'name', 'provider'], postgresql_nulls_not_distinct=False)
    op.drop_column('inventoryitems', 'description')
    op.drop_table('inventoryitem_supplier_association')
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
